apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cerebro
  name: cerebro-gui-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cerebro
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      containers:
      - args:
        - -Dconfig.file=/etc/cerebro/application.conf
        image: lmenezes/cerebro:0.9.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 150
        name: cerebro
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 150
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 300
        # resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/db/cerebro
          name: db
        - mountPath: /etc/cerebro
          name: config
        - mountPath: /opt/cerebro/logs/
          name: logs
        - mountPath: /tmp
          name: tmp
        resources:
          limits:
            cpu: 400m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 100Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: db
      - emptyDir: {}
        name: cerebro-gui
      - configMap:
          defaultMode: 420
          name: cerebro-gui
        name: config
      - emptyDir: {}
        name: logs
      - emptyDir: {}
        name: tmp